name: Deploy Streamlit App to Azure using Credentials

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: test-app-rajat-237w618723
  AZURE_RESOURCE_GROUP: Agentic-AI-RG
  AZURE_APP_SERVICE_PLAN: test-app-rajat-237w618723
  AZURE_LOCATION: eastus

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Create App Service Plan if not exists
        id: create_app_service_plan
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az appservice plan create --name ${{ env.AZURE_APP_SERVICE_PLAN }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --sku B1 --is-linux --location ${{ env.AZURE_LOCATION }}
        continue-on-error: true

      - name: Create Web App if not exists
        id: create_web_app
        run: |
          az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az webapp create --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_SERVICE_PLAN }} --runtime "PYTHON|3.9"
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd Python/src
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make startup.sh executable
        run: |
          cd Python/src  
          chmod +x startup.sh

      - name: Zip the application
        run: |
          cd Python/src
          zip -r app.zip . -x '*.git*'

      - name: Deploy to Azure via Kudu API
        run: |
          cd Python/src
          curl -X POST "https://${{ env.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy" \
          -u "${{ secrets.AZURE_USERNAME }}:${{ secrets.AZURE_PASSWORD }}" \
          --data-binary @app.zip

      - name: Configure startup command
        run: |
          az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --startup-file "Python/src/startup.sh"
